version: "3.9"
services:
  php:
    build:
      context: .
      dockerfile: Hermitage.Containerfile
    image: docker.io/nanemo/hermitage-php:1.0.1
    volumes:
      - type: volume
        target: /app
        source: php-code
      - type: bind
        target: /app/.env
        source: .env.example

  nginx:
    build:
      context: .
      dockerfile: Nginx.Containerfile
    image: docker.io/nanemo/hermitage-nginx:1.0.0
    ports:
      - "8080:8080"
    volumes_from:
      - "php"
volumes:
  php-code: