---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "default.fullname" . }}-nginx-config
  labels:
    {{- include "default.labels" . | nindent 4 }}
{{- with .Values.nginxConfig }}
data:
  {{- toYaml . | nindent 2 }}
{{- end -}}