---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "default.fullname" . }}-dotenvfile
  labels:
    {{- include "default.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.dotenv }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end -}}